baseURL: /
languageCode: en-us
title: Heart Safe Motherhood
theme: hugo-fresh-mod

params:
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: Heart Safe Motherhood
    # Hero subtitle (optional)
    subtitle: Better data. Smarter action. Brighter outcomes. 
    # Button text
    buttontext: Learn More
    # Where the main hero button links to
    buttonlink: "#section7"
    # Hero video
    image: https://www.dropbox.com/s/qqdvv82sb047562/Penn%20SOI%20-%20Heartsafe%20Motherhood.mp4?raw=1
    # image placeholder for video (from /images/illustrations/icons/placeholder.png)
    # text below explaing HSM
    subtitle2: Heart Safe Motherhood is an evidence-based program to improve the health outcomes and experience of postpartum women with hypertension
    # Footer logos (from /images/logos/clients/___.svg)
    clientlogos:
    - flu
    - Statin
    - generic
    - mm
    - cardiac
    - screening
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: Why Heart Safe Motherhood?
    url: /#section1
  - title: The Evidence
    url: /#section3
  - title: Program Features
    url: /#section4
  - title: The Team
    url: /#section6
  - title: Awards
    url: /#section2
  - title: Learn More
    url: /#section7
    button: true
  sidebar:
    # Logo (from /images/logos/___.svg)
    logo: fresh-square
    sections:
    - title: User
      icon: user
      links:
      - text: Profile
        url: /
      - text: Account
        url: /
      - text: Settings
        url: /
    - title: Messages
      icon: envelope
      links:
      - text: Inbox
        url: /
      - text: Compose
        url: /
    - title: Images
      icon: image
      links:
      - text: Library
        url: /
      - text: Upload
        url: /
    - title: Settings
      icon: cog
      links:
      - text: User settings
        url: /
      - text: App settings
        url: /
  section1:
    title: Why Heart Safe Motherhood?
    subtitle: Hypertension is a leading cause of maternal morbidity and mortality.  Heart Safe Motherhood was created to improve care for mothers with hypertension after delivery and change those statistics.
    tiles:
    - title: Preventable Death
      icon: person
      text: 1 in 5 of the 700 maternal deaths each year in the US are linked to preeclampsia.
      url: /
      buttonText: 
    - title: Preventable Disease
      icon: multiply
      text: For every maternal death in the United States, there are about 100 episodes of severe maternal morbidity.
      url: /
      buttonText: 
    - title: ACOG Guidelines
      icon: acogtiming_grey
      text: Guidelines recommend monitoring BP at 72 hours and 7-10 days postpartum in at-risk women.
      url: /
      buttonText:
    tiles2: 
    - title: Patient-Centered
      icon: telemedicine
      text: With a new baby at home, frequent in-person visits are not feasible. We can care for women in a better way.
      url: /
      buttonText: 
    - title: Provider-Friendly
      icon: doctor
      text: Heart Safe Motherhood makes remote monitoring easy so that you can focus on caring for your patients.
      url: /
      buttonText:
    - title: Evidence-Based Model
      icon: badge
      text: Our model is supported by published results from a [randomized controlled trial](https://qualitysafety.bmj.com/content/27/11/871.long) and [rapid-cycle testing](https://www.mdedge.com/jcomjournal/article/146153/womens-health/rapid-cycle-innovation-testing-text-based-monitoring).
      url: /
      buttonText: 
  section2:
    title: Awards
    subtitle: Multiple national and innovation awards
    features:
    - title: 
      text: 
      icon: aha2
    - title: 
      text: 
      icon: aheart2
    - title: 
      text: 
      icon: council2
    - title: 
      text: 
      icon: vizient2
    - title: 
      text: 
      icon: pbj
  section3:
    title: The Evidence
    subtitle: Proven. Used at Scale.
    tiles:
    - title: 
      icon: results
      text1: In 2017, we completed a [randomized controlled trial](https://qualitysafety.bmj.com/content/27/11/871.long) comparing Heart Safe Motherhood to the usual care of one-time, office-based blood pressure checks. 
      text2: We found an increase in our ability to obtain at least one blood pressure within ten days of discharge in 92% of patients using text messaging, compared to 44% in usual care.  We met ACOG guidelines in 80% of our patients.  Readmissions dropped to zero percent among remote monitored women in the trial. 
      text3: Heart Safe Motherhood not only enables real-time notification of severely elevated blood pressures, but also sheds light on blood pressure trends over time and allows providers to request additional blood pressure readings to follow-up on medication changes.  By adapting algorithms from office visit care, we are able safely to start antihypertensive medications remotely prior to the development of morbidity and direct the right women to in-person care at the right time.
      url: /
      buttonText:
  section4: 
    title: Program Features
    subtitle: Codifying Shared Knowledge
    icon1: patient
    icon2: provider
    tiles:
    - title: Patient engagement
      text: On the day after discharge, patients start on a remote monitoring protocol with automated reminders and feedback over a ten-day surveillance period enabled by [Way to Health](https://www.waytohealth.org), a Penn-developed platform for evidence-based, personalized engagement strategies.
    - title: Efficient automation
      text:  Providers focus on the information they need to know through alerts and dashboards.  Providers are alerted only when blood pressures are high enough to necessitate intervention.
    - title: Real-world expertise
      text: The Heart Safe Motherhood approach to patient identification, education, engagement, monitoring, and management was developed over four years to maximize impact, convenience, ease of use, and patient safety.
    - title: Continual innovation
      text: Heart Safe Motherhood is continuously evolving as we find new ways to engage patients, improve provider experience, and maximize impact through real-world implementations and innovative research. 
  section5:
    title: Contact us for a demo
    subtitle: ICYMI
    image: illustrations/mockups/mockup2-min.png
    buttonText: 
    buttonLink: "#"
  section6:
    title: The Team
    subtitle: We are Maternal Fetal Medicine specialists with an interest in preeclampsia who care deeply about our patients, research, and innovation before, during, and after pregnancy.
    clients:
    - name: Sindhu Srinivas, MD, MSCE
      quote: 
      job: Director, Obstetrical Services, Hospital of the University of Pennsylvania. <br/><br/>Vice Chair of Quality and Safety, Department of Obstetrics and Gynecology. <br/> <br/>Associate Professor of Obstetrics and Gynecology. <br/><br/>Co-Founder and Medical Director, Heart Safe Motherhood
      img: sindhusrinivasheadshot
      link: https://www.pennmedicine.org/providers/profile/sindhu-srinivas
    - name: Adi Hirshberg, MD
      quote: 
      job: Assistant Professor of Clinical Obstetrics and Gynecology. <br/><br/>Co-Founder and Director of Clinical Operations, Heart Safe Motherhood
      img: adihirshbergheadshot
      link: https://www.pennmedicine.org/providers/profile/adi-hirshberg
  footer:
    # Logo (from /images/logos/___)
    logo: nc.svg
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
    - link: https://pennmedicine.org
      icon: pennmed.png
    - link: http://www.uphs.upenn.edu/obgyn/
      icon: pennmedicineobgynlogo.svg
    - link: https://healthcareinnovation.upenn.edu/
      icon: chci2.png
    - link: http://waytohealth.org/
      icon: waytohealth2.png
    bulmalogo: false
    product:
    - text: Discover features
      link: /
    - text: Why choose our product?
      link: /
    - text: Compare features
      link: /
    - text: Our roadmap
      link: /
    - text: Request features
      link: /
    docs:
    - text: 
      link: /
    - text: User guides
      link: /
    - text: Admin guide
      link: /
    - text: Developers
      link: /
    blogroll:
    - text: Latest news
      link: /
    - text: Tech articles
      link: /
    - text: Video blog
      link: /